name: multiple event triggers

on:
  push:
    branches:
      - master
  workflow-dispatch:

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - name: greeting
        run: echo "Hello world"
