name: my first workflow

on: workflow_dispatch

jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line linux script
        run: |
          echo "hello github actions"
          date

  build-on-windows:
    runs-on: windows-latest

    steps:
      - name: Run a multi-line windows script
        run: |
          echo "hello github actions"
          Get-Date
